# Generated by Django 5.2.1 on 2025-05-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimerecord',
            name='case_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='investigating_officer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='suspect_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='suspect_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='victim_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='victim_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
