# Generated by Django 5.2.1 on 2025-06-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_records', '0002_crimerecord_case_priority_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crimerecord',
            old_name='investigating_officer',
            new_name='victim_occupation',
        ),
        migrations.RemoveField(
            model_name='crimerecord',
            name='case_priority',
        ),
        migrations.RemoveField(
            model_name='crimerecord',
            name='severity',
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='court_case_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='evidence_chain_of_custody',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='evidence_collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='evidence_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='evidence_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='evidence_type',
            field=models.CharField(blank=True, choices=[('WEAPON', 'Weapon'), ('DOCUMENTS', 'Documents'), ('CCTV', 'CCTV Footage'), ('DNA', 'DNA Evidence'), ('FINGERPRINTS', 'Fingerprints'), ('PHYSICAL', 'Physical Evidence'), ('DIGITAL', 'Digital Evidence'), ('BIOLOGICAL', 'Biological Evidence'), ('TRACE', 'Trace Evidence'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='fir_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='fir_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='suspect_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='suspect_gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='suspect_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='suspect_status',
            field=models.CharField(blank=True, choices=[('ARRESTED', 'Arrested'), ('AT_LARGE', 'At Large'), ('KNOWN', 'Known'), ('UNKNOWN', 'Unknown')], max_length=20),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='victim_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='victim_gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='victim_marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='crimerecord',
            name='suspect_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='crimerecord',
            name='victim_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
