# Generated by Django 5.2.1 on 2025-06-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_records', '0003_rename_investigating_officer_crimerecord_victim_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimerecord',
            name='evidence_image',
            field=models.ImageField(blank=True, null=True, upload_to='evidence_images/'),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='suspect_image',
            field=models.ImageField(blank=True, null=True, upload_to='suspect_images/'),
        ),
    ]
