# Generated by Django 5.2.1 on 2025-06-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_records', '0004_crimerecord_evidence_image_crimerecord_suspect_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimerecord',
            name='officer_badge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='officer_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='officer_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='officer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
