# Generated by Django 5.2.1 on 2025-06-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_records', '0005_crimerecord_officer_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimerecord',
            name='witness_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='witness_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='witness_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='witness_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='crimerecord',
            name='evidence_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crimerecord',
            name='evidence_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
