# Generated by Django 5.2.1 on 2025-06-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_records', '0006_crimerecord_witness_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimerecord',
            name='witness_address',
        ),
        migrations.RemoveField(
            model_name='crimerecord',
            name='witness_contact',
        ),
        migrations.RemoveField(
            model_name='crimerecord',
            name='witness_name',
        ),
        migrations.RemoveField(
            model_name='crimerecord',
            name='witness_statement',
        ),
        migrations.AlterField(
            model_name='crimerecord',
            name='case_number',
            field=models.CharField(help_text='Unique case number for the crime record', max_length=50, unique=True),
        ),
    ]
